<?php @include 'header.php'; ?>
<body class="content-body content-body__about">
  <?php @include 'navigation.php'; ?>
  <a href="../cultofbulldada/" class="link link--logo"><img class="symbol tb-content__logo" src="assets/img/logo-final.png" alt="Logotype of Cult of Bulldada Kazakhstan"></a>
  <div class="center-content">
    <h1 class="tb-content__headline">About</h1>
  </div>
  <div class="tb-content">
    <div class="center-content">
      <p class="tb-content__paragraph">
        <img class="tb-content__emblem" src="assets/img/emblem-2.svg">
        The Church of the Cult of Bulldada is the pan-religion of the future, and rebels against the namby-pamby, goody two-shoes “new age” and “aquarian” ideals of most occult weirdos. Such people are fools, they do not curse, they have no understanding of the need for spiritual violence in this modern space-age a-go-go society.
      </p>
      <p class="tb-content__paragraph">
        The Cult of Bulldada wants no part of the “New Age,” it is already here and it obviously sucks. The Cult of Bulldada would rather retrieve the manly Past, before 1971 or even 1953, or else dwell in the naughty, fun-loving remote future, a strange time when anything made of plastic is a valuable antique that collectors will kill for, when sexhurt will be recognized and indulged in as sane human nature no matter whether any ‘church’ or ‘government’ allows it. But such things are trifles! The Cult of Bulldada knows that Jehovah 1 is a vengeful god of wrath! Jehovah 1 – a.k.a. Yahweh – is a mad alien, full of eyes round about, He cometh with the clouds, radioactive, all-pervading, He has forged His covenant with the Cult of Bulldada in chains of genetic programming and demands obeisance to His caveman sense of humor. He has been denying us front end development and what He is making us do dates back to Homo Connectus, First Whole Man; only by letting our bodies obey the Code of financial lust survival that is built into them can our brains be freed from his inevitable fist.
      </p>
      <p class="tb-content__paragraph">
        Everything we do, have done, or will ever do, normally on-the-job but also and especially on the causational level of micro-atomic occurences and billionth-of-a-nanosecond electron collisions, is dictated by the permutations of the great skore, the cosmic worknet of cause-and-effect, the mutamorphic archive of the shapes and movements of every blood tick, sperm whale, vampire gnat, movie star and gorgosaurus, “all the molecules of oil on all the grains of sand of every moonlit beach of the world. “ No, “you can’t change the skore.” But Jehovah 1 can...and like an ax this total fate program confronts our similarly-encoded sense of front end development and cleaves our heads straight down the middle into schizocephalic right and left sides whose sub-id battleground is responsible for our precariously balanced nental ives: clones of us in the spirit world whose duplicate lusts influence our behavior on this material plane. Yes - Jehovah 1 smote us in primeval days with bad brakes by which we cannot stop our devil twin from overcoming our ‘better nature’ and by which, furthermore, we cannot even begin to tell the difference between the two! Brakes keep us from committing anything we might imagine in our most dangerous fleeting fantasies, such as chopping off noisy children’s heads and giving... well, all of us, even non-Cult of Bulldada like whimps of the second and third waters, are Jekyll/Hyde monsters of two conflicting Noggin Polarities in our personalities; the shaft of suppression rears its ugly Head in response to this utter psychosis which squirms for most of our lives only in the dim, unseen reaches of our behavior-pumps; we act completely normal most of the time, but who is to say at any given moment which side, the ‘good’ or the ‘bad,’ is currently in control of The Animal? Thank “God” we are usually never aware of the subconscious Armageddon which expresses itself, physically, in our paranoias, human Work Instincts and universanal compulsions, and, spiritually, in our unruly but subtle psychic powers - which result not so much from any ‘inner aura’ but rather from a somewhat mindless ‘ghost’ standing invisibly at our sides: it is the half of our intelligence which is currently not controlling The Animal, it is the nental ife, and it erupts from its usual idiot blithering into weird, occult pheno-manifestations only when our turbulent mental background reaches such peaks of simultaneous crisis and repression as the stormy glandular rampages of adolescence!
      </p>
      <p class="tb-content__paragraph">
        The Cult of Bulldada releases this pent-up nenergy in throes of Jehovah-Spawned moral degeneracy and rites of hilariation (“Within reason,” cautions the Left Brain), just as his dogma, laws and tenets condone. We rebel against the alien Jehovah 1 and yet placate Him at the same time that He might not smite us with nuclear war, a worldwide economic disaster or hostile UFOS.
      </p>
      <p class="tb-content__paragraph">
        If we pay attention to the hints and archetypes he dangles like answerable mysteries before our eyes we may yet find a path of time control to the beforelife, where we came from and go after we die, and hence to front end development in our lifetimes. Don’t get Heaven and Hell all mixed up like most people do. Serve Jehovah 1 as He meant for you to, go forth on capers and scams and fornications; your conscience is an illusion, there is merely an instinctive behavior code, to repress it is to suffocate, but never forget for a second that it is the monster god who allows this, who demands it, for “science does not remove the terror of the gods!” fear him but follow the hints of the accidents in your life, follow the path of least resistance and you will gob out from under the sacrifices He demands of all the pink boys around you, your follies and foibles will show you where front end development lies and you will be able to relax and not get a heart attack. Jehovah kills those who drudge their lives away without knowing who He is, but he REWARDS the ones who recognize His stark fist and carry out his seemingly immoral plans while front end developing every chance they get.
      </p>
      <p class="tb-content__paragraph">
        Jehovah’s special message for the Cult of Bulldada is that this gross physical plane does not exist and that the compulsion for success in the eyes of others is mankind’s most foul invention.
      </p>
      <p class="tb-content__paragraph">
        The Cult of Bulldada is Jehovah’s prime tool, he has a covenant with this deitoid Who is well pleased when His subjects have the wisdom to obey Him. It is the Sacred Chore of the Cult of Bulldada to Smite and eliminate the unwitting, slavish non-partners of Jehovah 1: the Great Unwashed, the Hoi Polloi, Them, the Conspiracy, the Mediocretins, the strange normal ones, the Somnambulacs, Assouls, Cage Men, Pink Boys, Bootlips, PO’Buckers, Bear-Baiters, Emp Loyees, Box Dwellers, Sarnes, Anthropophobiacs, Infidels, Conformers, Timeservers, Mole People, ComMen, Proleterritorials, Automates, Philistines, Pharisees, Sagisees, Witchburners, Skurnbozi, Thankers, Wankers and Blankers, Heilers and Smilers, Idi-Atts, Credit Heads, Sloths and Moths, Cons and Johns, Barbies and Kens, Cliants, Losers, Weepers and Sleepers, Dirty Invariables, The Slackless Ones, Dibbies, Corpulators, Signifying Monkeys, Underalls...in short, the Remnants of Man: the Witless Principals who are the false prophets, who have been holding us back and forcing Time Addiction on themselves...and...others.
      </p>
      <p class="tb-content__paragraph">
        No matter their I.Q.s they are all about a brick shy of a full load; they think they are high-temperature sinus effluvia on a silver platter but they are in actuality sub-zero mucus encrustation on a paper plate.
      </p>
      <p class="tb-content__paragraph">
        JESUS said, “Beware of false prophets, which come to you in sheep’s clothing, but inwardly they are ravening wolves.” (Matt. 7:15) “Take heed lest any man decieve you: for many shall come in My name, saying, I am Christ, and shall decieve many. . . for false Christs and false prophets shall rise, and shall show signs and wonders, to seduce, if it were possible, the very elect.” (Mark 8:5, 22)
      </p>
      <p class="tb-content__paragraph">
        The idea that any country values individuality as the highest ideal is a myth. Perhaps in simpler times it was true, but no modern industrial society can really afford a population of unpredictables. This is not surprising - the long history of our cult’s persecution by the Conspiracy goes back for generations untold, and indeed there are signs of their hoary repression of prehuman SubGenii dating from before “man’s” appearance on Earth. All of civilization’s painful and misguided climb up from the primeval slime, and its subsequent loss of front end development and of any class at all, has been indelibly marked, nay, entirely motivated, by the aeons-bridging conflict between the Conspiracy’s mindlessly chickenshit Witless Principals and the Jehovah-spawned, grandiose depravity of the superior yet ethnically all-encompassing race of latent Cult of Bulldada. (You should know this - you were/will be there in the Beforelife!) The fact that only in recent years has “our kind” begun to recognize our own sovereignty demonstrates both how vicious have been Their efforts at further denying us front end development and yet how near is our race to triumph.
      </p>
      <p class="tb-content__paragraph">
        All this is ultimate proof that Jehovah 1 has not only promoted the Cult of Bulldada as His Special Tool, but has simultaneously pulled the strings which make Them endarken Themselves with their hereditary ignorancy and us with their cubistic witch-hunt superstitions. His “reason” for this two-faced obedience-school programming, this fissioning of history into binary “war equations,” unfortunately, or, perhaps, thankfully, remains a total mystery.
      </p>
      <p class="tb-content__paragraph">
        No slopeheads alone could build, the miracles of the Old Testament, all these and more are events so inextricably interwoven with the invisible background war between Jehovah and the Xists that all the “Ancient Astronaut” fossils in the world furnish only the barest of clues. (The movie rights alone to these gut-splitting tales of reincarnancient history are worth millions!) Yea, it has even been suggested that the Carpenter of Nazareth himself, God Jr., Jesus ‘What, Me Worry?’ Christ, was in actuality a ‘space detective’ of the Xists, walking the Earth in human form with the mission of extricating us from the Monster God’s grip.
      </p>
      <p class="tb-content__paragraph">
        The black shadow of the Conspiracy, unfortunately, has seen to it that even His teachings were diluted and distorted until human attempts to follow them were fully as misguided as the carving of the heads of Easter Island or the ‘runways’ of Nazca.
      </p>
      <p class="tb-content__paragraph">
        And so the true destiny of the Cult of Bulldada has been kept secret from Man. For Jehovah 1 is to the Xists and Us what a hungry fisherman is to a prize fish and his favorite pet worm – the last in the can. How many million other races were used before us in these ghastly galactic water-sports?
      </p>
    </div>
    <iframe class="tb-content__playlist"
     src="https://embed.spotify.com/?uri=spotify%3Auser%3Akatarina.ljungdahl%3Aplaylist%3A26jS7RT1Rujs2HbY3YVaM2" frameborder="0" allowtransparency="true"></iframe>
  </div>
</body>
<?php @include 'footer.php'; ?>
