<?php @include 'header.php'; ?>
<body class="tb-content">
  <h1 class="tb-content__headline">Bulldada</h1>
  <p class="tb-content__paragraph">
  Bulldada is the nearly unexplainable label for that mysterious quality that impregnates ordinary things with meaning for the Cult of bulldada no matter how devoid of value they may appear to The Others. Seeing in the vivisecting light of bulldada, we recognize that the most awe-inspiring artifacts of our civilization are not the revered artsy-fartsy pieces of “culture” displayed in our swankest art museums, universities and concert halls - as the Conspiracy would have us believe! - but are instead to be found in such icons as low-budget exploitation movies, lurid comic books, all-nite TV, sleazy Paperbacks of the Gods, certain bizarre billboards and pulp magazine ads, and literally any other fossil of raw humanity in all its shit-kickingly flawwed glory.</p>
  <p class="tb-content__paragraph">Bulldada shows us that cheesiness tells the Truth and gives good Front end development whereas status-mongered slickness is merely a sheen of sham value dangled as bait for the hungry dollars of the idiot bourgeois. The Cult of bulldada is not interested in dignified “Learning” or even science fiction - no, what he craves is greasy sci-fi. He is a veritable scholar of cheepnis! For when a certain level of shoestring-budget “exquisite badness” is descended to on the Rungs of Art, one hits’the cut-off point where true bulldada begins, the ‘edge valve’ where the Cult of bulldada starts finding almost religious interpretation for the results of atrocious craftsmanship, the point after which a work’s quality as a piece of bulldada increases in inverse proportion to its ability to yell a coherent story. The less sophisticated a motion picture (our highest art form) becomes, for instance, the more dismemberingly eternal are the truths between the lines. Mars needs women! Panic in year zero! Often, they contain inadvertent prophecies – as well as unexpected background appearances of Klaatu! Plan nine from outer space! Mondo bizarro!
  </p>
</body>
<?php @include 'footer.php'; ?>
